import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { CP, request } from '../api/client';
import { ErrorNotice } from '../components/Shared';
type Row = { id: string; title?: string; decision_key?: string; version?: number; status?: string; state?: string; candidate?: { title: string; problem: string; proposal: string; risk: string; alternatives: string[]; consequences: string[]; acceptanceCriteria: { criterionKey: string; description: string; evidenceRule: string }[]; unresolvedQuestions: string[] }; messages?: { id: string; content: string }[]; actions?: { action: string; comment: string }[] };
function useItems(path: string) { return useQuery({ queryKey: ['design', path], queryFn: () => request<Row[]>(`${CP}/${path}`), refetchInterval: 10_000 }); }
export function Design({ owner }: { owner: boolean }) {
 const sessions = useItems('design/sessions'); const client = useQueryClient();
 const [title, setTitle] = useState(''); const [sessionId, setSessionId] = useState('');
 const [risk, setRisk] = useState('MEDIUM'); const [alternatives, setAlternatives] = useState(''); const [consequences, setConsequences] = useState(''); const [questions, setQuestions] = useState('');
 const lines = (s: string) => s.split('\n').map(v => v.trim()).filter(Boolean);
 const [message, setMessage] = useState(''); const [proposal, setProposal] = useState(''); const [problem, setProblem] = useState(''); const [criterion, setCriterion] = useState(''); const [evidence, setEvidence] = useState('');
 const selected = useQuery({ queryKey: ['design', sessionId], enabled: !!sessionId, queryFn: () => request<Row>(`${CP}/design/sessions/${sessionId}`), refetchInterval: 10_000 });
 const update = () => void client.invalidateQueries({ queryKey: ['design'] });
 const create = useMutation({ mutationFn: () => request<Row>(`${CP}/design/sessions`, 'POST', { title }), onSuccess: r => { setSessionId(r.id); update(); } });
 const send = useMutation({ mutationFn: () => request(`${CP}/design/sessions/${sessionId}/messages`, 'POST', { content: message }), onSuccess: () => { setMessage(''); update(); } });
 const propose = useMutation({ mutationFn: async () => {
  let discussion = await request<Row>(`${CP}/design/sessions/${sessionId}`);
  if (message.trim() && !discussion.messages?.some(m => m.content === message.trim())) {
   await request(`${CP}/design/sessions/${sessionId}/messages`, 'POST', { content: message.trim() });
   discussion = await request<Row>(`${CP}/design/sessions/${sessionId}`);
  }
  return request<Row>(`${CP}/design/sessions/${sessionId}/decision-candidates`, 'POST', { title: discussion.title, problem, proposal, risk, alternatives: lines(alternatives), consequences: lines(consequences), affectedAreas: [], acceptanceCriteria: [{ criterionKey: 'AC-1', description: criterion, verificationType: 'TEST', evidenceRule: evidence }], unresolvedQuestions: lines(questions), sourceMessageIds: discussion.messages?.map(m => m.id) ?? [] });
 }, onSuccess: () => { setMessage(''); update(); } });
 return <section className="design-page"><span className="eyebrow">DESIGN TO DELIVERY</span><h1>Explore, then decide.</h1><p>Record a discussion and submit a proposal for owner review. This first release supports manual proposals; automated extraction and external implementation are pending.</p><ErrorNotice error={sessions.error} />
 {owner && <form onSubmit={e => { e.preventDefault(); create.mutate(); }}><label>Discussion title<input required maxLength={200} value={title} onChange={e => setTitle(e.target.value)} /></label><button className="primary" disabled={create.isPending}>New discussion</button><ErrorNotice error={create.error} /></form>}
 <label>Discussion<select value={sessionId} onChange={e => setSessionId(e.target.value)}><option value="">Choose a discussion</option>{sessions.data?.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}</select></label>
 <ErrorNotice error={selected.error} />{selected.data && <><h2>{selected.data.title}</h2>{selected.data.messages?.map(m => <p key={m.id}>{m.content}</p>)}
 {owner && <><form onSubmit={e => { e.preventDefault(); send.mutate(); }}><label>Discussion note<textarea required maxLength={20000} value={message} onChange={e => setMessage(e.target.value)} /></label><button disabled={send.isPending}>Add note</button><ErrorNotice error={send.error} /></form>
 <form onSubmit={e => { e.preventDefault(); propose.mutate(); }}><h2>Decision proposal</h2><label>Problem<textarea required value={problem} onChange={e => setProblem(e.target.value)} /></label><label>Proposed change<textarea required value={proposal} onChange={e => setProposal(e.target.value)} /></label><label>Risk<select value={risk} onChange={e => setRisk(e.target.value)}>{['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map(r => <option key={r}>{r}</option>)}</select></label><label>Alternatives considered (one per line)<textarea value={alternatives} onChange={e => setAlternatives(e.target.value)} /></label><label>Consequences (one per line)<textarea value={consequences} onChange={e => setConsequences(e.target.value)} /></label><label>Unresolved questions (one per line)<textarea value={questions} onChange={e => setQuestions(e.target.value)} /></label><label>Testable acceptance criterion<input required value={criterion} onChange={e => setCriterion(e.target.value)} /></label><label>Required evidence<input required placeholder="e.g. test suite and report path" value={evidence} onChange={e => setEvidence(e.target.value)} /></label><p>All discussion notes are linked as provenance. Open questions block acceptance. Use the structured API for additional criteria and affected areas.</p><p>{message.trim() ? 'Your discussion note will be saved automatically when you submit.' : !selected.data.messages?.length ? 'Add a discussion note above to enable submission.' : 'Ready to submit with saved discussion notes.'}</p><button className="primary" disabled={propose.isPending || send.isPending || (!selected.data.messages?.length && !message.trim())}>Submit for owner review</button><ErrorNotice error={propose.error} />{propose.data && <p><Link to={`/decisions/${propose.data.id}`}>Review {propose.data.decision_key}</Link></p>}</form></> }</>}
 </section>;
}
export function Decisions() { const items = useItems('decisions'); return <section className="design-page"><h1>Decisions</h1><p>Versioned proposals and their owner decisions.</p><ErrorNotice error={items.error} />{items.data?.map(r => <p key={r.id}><Link to={`/decisions/${r.id}`}>{r.decision_key} · v{r.version}</Link> — {r.status}</p>)}{items.data?.length === 0 && <p>No decisions yet. <Link to="/design">Start a discussion</Link>.</p>}</section>; }
export function Decision({ owner }: { owner: boolean }) {
 const { id } = useParams(); const client = useQueryClient(); const [comment, setComment] = useState(''); const [draftJson, setDraftJson] = useState('');
 const item = useQuery({ queryKey: ['design', 'decision', id], queryFn: () => request<Row>(`${CP}/decisions/${id}`), refetchInterval: 10_000 });
 const capabilities = useQuery({ queryKey: ['design', 'capabilities'], queryFn: () => request<{ durableGateEnabled: boolean; limitation: string }>(`${CP}/design/capabilities`) });
 const action = useMutation({ mutationFn: (action: string) => request(`${CP}/decisions/${id}/${action}`, 'POST', { comment }), onSuccess: () => void client.invalidateQueries({ queryKey: ['design'] }) });
 const submit = useMutation({ mutationFn: () => request(`${CP}/decisions/${id}/submit`, 'POST', JSON.parse(draftJson)), onSuccess: () => void client.invalidateQueries({ queryKey: ['design'] }) });
 const r = item.data; const c = r?.candidate;
 return <section className="design-page"><h1>{r?.decision_key ?? 'Decision'} · v{r?.version}</h1><ErrorNotice error={item.error} /><p>{r?.status}</p>{c && <><h2>{c.title}</h2><h3>Problem</h3><p>{c.problem}</p><h3>Proposal</h3><p>{c.proposal}</p><p>Risk: {c.risk}</p><h3>Acceptance</h3>{c.acceptanceCriteria.map(a => <p key={a.criterionKey}>{a.criterionKey}: {a.description}<br />Evidence: {a.evidenceRule}</p>)}<h3>Alternatives</h3>{c.alternatives.map(a => <p key={a}>{a}</p>)}<h3>Consequences</h3>{c.consequences.map(a => <p key={a}>{a}</p>)}<h3>Open questions</h3>{c.unresolvedQuestions.length ? c.unresolvedQuestions.map(q => <p key={q}>{q}</p>) : <p>None recorded.</p>}</>}
 <p>{capabilities.data?.limitation}</p>{!capabilities.data?.durableGateEnabled && <p>Owner actions are unavailable until the durable Temporal gate is enabled.</p>}
 {owner && r?.status === 'PENDING_OWNER' && <><label>Decision reason<textarea value={comment} onChange={e => setComment(e.target.value)} maxLength={3000} /></label>{['accept', 'revise', 'reject'].map(a => <button key={a} disabled={!comment.trim() || action.isPending || !capabilities.data?.durableGateEnabled || (a === 'accept' && !!c?.unresolvedQuestions.length)} onClick={() => action.mutate(a)}>{a}</button>)}<ErrorNotice error={action.error} /></>}
 {owner && r?.status === 'DRAFT' && <><h3>Revise draft</h3><button onClick={() => setDraftJson(JSON.stringify(c, null, 2))}>Load proposal for editing</button><label>Structured proposal<textarea rows={16} value={draftJson} onChange={e => setDraftJson(e.target.value)} /></label><button disabled={!draftJson.trim() || submit.isPending} onClick={() => submit.mutate()}>Submit revised proposal</button><ErrorNotice error={submit.error} /></>}
 <p>{c?.unresolvedQuestions.length ? 'Acceptance is blocked by open questions. Request a revision to resolve them.' : ''}</p><h3>Owner action history</h3>{r?.actions?.map((a, i) => <p key={i}>{a.action}: {a.comment}</p>)}<Link to="/delivery">View delivery runs</Link></section>;
}
export function Delivery() { const items = useItems('delivery-runs'); return <section className="design-page"><h1>Delivery runs</h1><p>Workflow state reported by the backend. External implementation and merging are not enabled in this release.</p><ErrorNotice error={items.error} />{items.data?.map(r => <p key={r.id}><Link to={`/delivery/${r.id}`}>{r.id}</Link> — {r.state}</p>)}{items.data?.length === 0 && <p>No delivery runs.</p>}</section>; }
export function DeliveryDetail() { const { id } = useParams(); const item = useQuery({ queryKey: ['design', 'run', id], queryFn: () => request<Row>(`${CP}/delivery-runs/${id}`), refetchInterval: 10_000 }); return <section className="design-page"><h1>Delivery run</h1><ErrorNotice error={item.error} /><p>{item.data?.state}</p><p>Implementation evidence and merge approval will appear when the governed delivery adapters are available.</p></section>; }
