import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Link } from 'react-router-dom';
import { api } from '../api/client';
import { date, Empty, ErrorNotice, Metric, money, PageHeading, Panel, Status } from '../components/Shared';

export function Approvals({ owner }: { owner: boolean }) {
  const approvals = useQuery({ queryKey: ['approvals'], queryFn: api.approvals });
  const [comments, setComments] = useState<Record<string, string>>({});
  const client = useQueryClient();
  const decision = useMutation({ mutationFn: ({ id, action }: { id: string; action: 'approve' | 'deny' }) => api.decide(id, action, comments[id]?.trim() || ''), onSuccess: () => { void client.invalidateQueries(); } });
  return <><PageHeading eyebrow="COMPANY / GOVERNANCE" title="Approval inbox" description="You decide what happens next. Every decision is recorded by the backend." /><ErrorNotice error={approvals.error || decision.error} /><div className="approval-list">{approvals.data?.items.map((item) => <Panel key={item.approvalId} title={item.actionType.replaceAll('_', ' ')} action={<Status value={item.riskLevel || item.status} />}><div className="approval-body"><p>{item.description || item.reason || 'A governed action requires your decision.'}</p><div className="approval-meta"><span>REQUESTED BY <strong>{item.requestingAgent || 'System'}</strong></span><span>ESTIMATED COST <strong>{item.estimatedCost === null ? 'Unavailable' : money(item.estimatedCost)}</strong></span><span>CREATED <strong>{date(item.createdAt)}</strong></span></div><Link className="detail-link" to={`/missions/${item.missionId}`}>{item.missionTitle || 'Inspect mission'} ↗</Link></div>{owner && <div className="approval-actions"><input aria-label={`Decision comment for ${item.actionType}`} placeholder="Decision note (optional)" value={comments[item.approvalId] || ''} onChange={(event) => setComments({ ...comments, [item.approvalId]: event.target.value })} /><button className="secondary" disabled={decision.isPending} onClick={() => { if (window.confirm(`Deny ${item.actionType}?`)) decision.mutate({ id: item.approvalId, action: 'deny' }); }}>Deny</button><button className="primary" disabled={decision.isPending} onClick={() => { if (window.confirm(`Approve ${item.actionType}?`)) decision.mutate({ id: item.approvalId, action: 'approve' }); }}>Approve action</button></div>}</Panel>)}{!approvals.data?.items.length && <Panel title="Your queue"><Empty title={approvals.isPending ? 'Loading approvals…' : 'All clear'} detail="There are no pending owner decisions." /></Panel>}</div></>;
}

export function Resources() {
  const budgets = useQuery({ queryKey: ['budgets'], queryFn: api.budgets });
  const costs = useQuery({ queryKey: ['costs'], queryFn: api.costs });
  return <><PageHeading eyebrow="COMPANY / ECONOMICS" title="Resources & spend" description="Understand usage, budget headroom, and the cost of each agent." /><ErrorNotice error={budgets.error || costs.error} /><div className="metrics-grid three"><Metric label="SPEND TODAY" value={costs.data ? money(costs.data.spendToday) : '—'} /><Metric label="THIS WEEK" value={costs.data ? money(costs.data.spendThisWeek) : '—'} /><Metric label="THIS MONTH" value={costs.data ? money(costs.data.spendThisMonth) : '—'} /></div>
    <div className="dashboard-grid"><Panel title="Budget health">{budgets.data?.budgets.length ? budgets.data.budgets.map((budget) => <div className="budget-row" key={budget.budgetId}><div><strong>{budget.name}</strong><Status value={budget.status} /></div><div className="progress"><span style={{ width: `${Math.min(100, Math.max(0, budget.utilizationPct))}%` }} /></div><small>{money(budget.committed)} committed · {money(budget.available)} available of {money(budget.limit)}</small></div>) : <Empty title="No budgets configured" detail="Budget controls are managed in the backend." />}</Panel>
      <Panel title="Spend by agent">{costs.data?.byAgent.length ? <div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={costs.data.byAgent.slice(0, 8)} layout="vertical" margin={{ left: 10, right: 20 }}><CartesianGrid stroke="#26354a" horizontal={false} /><XAxis type="number" stroke="#8190a5" tickFormatter={(value: number) => `$${value}`} /><YAxis type="category" dataKey="agentId" width={100} stroke="#8190a5" tick={{ fontSize: 11 }} /><Tooltip contentStyle={{ background: '#172236', borderColor: '#31415b', color: '#fff' }} formatter={(value: number) => money(value)} /><Bar dataKey="totalCost" fill="#62a9ff" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></div> : <Empty title="No usage recorded" detail="Agent costs appear after execution." />}</Panel></div>
    <Panel title="Agent economics"><div className="table-wrap"><table><thead><tr><th>AGENT</th><th>EXECUTIONS</th><th>FAILURES</th><th>TOKENS</th><th>AVERAGE COST</th><th>TOTAL SPEND</th></tr></thead><tbody>{costs.data?.byAgent.map((row) => <tr key={row.agentId}><td>{row.agentId}</td><td>{row.executionCount}</td><td>{row.failedCount}</td><td>{(row.inputTokens + row.outputTokens).toLocaleString()}</td><td>{money(row.averageCost)}</td><td>{money(row.totalCost)}</td></tr>)}</tbody></table>{!costs.data?.byAgent.length && <Empty title="No agent usage yet" />}</div></Panel></>;
}

export function Memory() {
  const [draft, setDraft] = useState('');
  const [term, setTerm] = useState('');
  const results = useQuery({ queryKey: ['memory', term], queryFn: () => api.memory(term), enabled: !!term, refetchInterval: false });
  return <><PageHeading eyebrow="INTELLIGENCE / CONTEXT" title="Memory explorer" description="Search the knowledge influencing decisions and inspect its provenance." /><form className="search-form" onSubmit={(event) => { event.preventDefault(); setTerm(draft.trim()); }}><input aria-label="Search memory" placeholder="Search company memory..." value={draft} onChange={(event) => setDraft(event.target.value)} /><button className="primary" type="submit" disabled={!draft.trim()}>Search memory</button></form><ErrorNotice error={results.error} /><div className="memory-results">{results.data?.results.map((item) => <Panel title={item.memoryType.replaceAll('_', ' ')} key={item.chunkId} action={<span className="subtle">{Math.round(item.finalScore * 100)}% relevance</span>}><p>{item.content}</p><div className="memory-meta"><span>Source: {item.source}</span><span>Conversation: {item.conversationId}</span><span>{date(item.createdAt)}</span></div></Panel>)}{!results.data?.results.length && <Panel title="Search results"><Empty title={term ? results.isPending ? 'Searching…' : 'No matching memories' : 'Explore what Genie knows'} detail={term ? 'Try a different search term.' : 'Search to inspect stored context and its source.'} /></Panel>}</div></>;
}

export function Audit() {
  const [missionId, setMissionId] = useState('');
  const audit = useQuery({ queryKey: ['audit', missionId], queryFn: () => api.audit(missionId || undefined) });
  return <><PageHeading eyebrow="COMPANY / ACCOUNTABILITY" title="Audit trail" description="Trace who acted, what happened, and which mission it affected." /><div className="filter-bar"><input aria-label="Filter by mission ID" placeholder="Filter by mission ID" value={missionId} onChange={(event) => setMissionId(event.target.value)} /></div><ErrorNotice error={audit.error} /><Panel title="Recent events" action={<span className="subtle">{audit.data?.totalElements ?? 0} entries</span>}><div className="timeline">{audit.data?.items.map((item) => <div className="timeline-item" key={item.eventId}><span className="timeline-dot" /><div><strong>{item.summary}</strong><small>{item.eventType.replaceAll('_', ' ')} · {item.actor} · {date(item.timestamp)}</small>{item.missionId && <Link className="detail-link" to={`/missions/${item.missionId}`}>View mission ↗</Link>}{item.correlationId && <code>{item.correlationId}</code>}</div></div>)}{!audit.data?.items.length && <Empty title={audit.isPending ? 'Loading audit trail…' : 'No audit entries found'} />}</div></Panel></>;
}

export function System({ owner }: { owner: boolean }) {
  const health = useQuery({ queryKey: ['health'], queryFn: api.health });
  const autonomy = useQuery({ queryKey: ['autonomy'], queryFn: api.autonomy });
  const stop = useQuery({ queryKey: ['stop'], queryFn: api.stop });
  const client = useQueryClient();
  const [reason, setReason] = useState('');
  const action = useMutation({ mutationFn: () => stop.data?.active ? api.clearStop(reason.trim()) : api.activateStop(reason.trim()), onSuccess: () => { setReason(''); void client.invalidateQueries(); } });
  return <><PageHeading eyebrow="SYSTEM / RUNTIME" title="System health" description="Connection status, local dependencies, and owner controls." /><ErrorNotice error={health.error || autonomy.error || stop.error || action.error} /><div className="metrics-grid three"><Metric label="BACKEND" value={health.data?.status || 'Unavailable'} note={health.data ? `${health.data.passed} passed · ${health.data.failed} failed` : 'Waiting for backend'} /><Metric label="AUTONOMY MODE" value={autonomy.data?.mode.replaceAll('_', ' ') || '—'} /><Metric label="EMERGENCY STOP" value={stop.data ? stop.data.active ? 'ACTIVE' : 'Inactive' : '—'} /></div>
    <div className="dashboard-grid"><Panel title="Service checks">{health.data?.checks.length ? health.data.checks.map((check) => <div className="list-row" key={check.name}><div className="row-main"><strong>{check.name}</strong><small>{check.message || `${check.durationMs} ms`}</small></div><Status value={check.status} /></div>) : <Empty title="No health checks available" />}</Panel>
      <Panel title="Owner emergency control"><p className="panel-copy">The global stop is persisted by the backend and prevents new autonomous execution. Clearing it does not restart work.</p><Status value={stop.data?.active ? 'ACTIVE' : 'INACTIVE'} />{owner && <div className="control-box"><label>Reason for {stop.data?.active ? 'clearing' : 'activating'}<input value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Required for audit" /></label><button className={stop.data?.active ? 'secondary' : 'danger-button'} disabled={!reason.trim() || action.isPending || !stop.data} onClick={() => { if (window.confirm(`${stop.data?.active ? 'Clear' : 'Activate'} global emergency stop?`)) action.mutate(); }}>{stop.data?.active ? 'Clear emergency stop' : 'Activate emergency stop'}</button></div>}</Panel></div></>;
}

export function Verticals({ name }: { name: string }) {
  return <><PageHeading eyebrow="VERTICAL APPLICATION" title={name} description="This workspace connects to governed services when their APIs are available." /><Panel title="Integration pending"><Empty title="No service connected" detail={`The ${name} backend contract has not been implemented in Genie Company OS. No sample data or unsafe controls are shown.`} /></Panel></>;
}
