import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { request, CP } from '../api/client';
import { date, ErrorNotice, money, PageHeading, Panel } from '../components/Shared';
import { tradingOutcome } from './tradingOutcome';

type Evaluation = { fingerprint: string; strategyVersion: string; passed: boolean; reason: string; training: Record<string, unknown>; validation: Record<string, unknown> };
type Report = { missionId: string; outcome: string; status: string; health: string; stopReason: string | null; configuration: Record<string, unknown>; configurationFingerprint: string; configurationApproved: boolean; evaluation: Evaluation | null; evaluationApproved: boolean; equity: number; netPnl: number; fees: number; slippage: number; drawdown: number; drawdownPercent: number; maximumDrawdown: number; peakEquity: number; targetProgressPercent: number; initialMarginUsed: number; maintenanceMargin: number; closedTrades: number; positions: Record<string, unknown>; orders: Record<string, unknown>[]; fills: Record<string, unknown>[]; liquidationPending: boolean; reportedAt: string; workerEnabled: boolean; feedConfigured: boolean };
type Event = { id: string; event_type: string; created_at: string; details: unknown };
const base = `${CP}/futures/missions`;
function Records({ title, value }: { title: string; value: unknown }) { return <details className="trading-evidence"><summary>{title}</summary><pre>{JSON.stringify(value, null, 2)}</pre></details>; }

export function Trading({ owner }: { owner: boolean }) {
  const [params, setParams] = useSearchParams();
  const id = params.get('mission') ?? '';
  const client = useQueryClient();
  const [config, setConfig] = useState('');
  const [dataset, setDataset] = useState('');
  const [bars, setBars] = useState('');
  const [logsOpen, setLogsOpen] = useState(false);
  const [decision, setDecision] = useState<'approve-configuration' | 'approve-evaluation' | null>(null);
  const list = useQuery({ queryKey: ['futures-list'], queryFn: () => request<{ missionId: string; status: string }[]>(base), enabled: owner, refetchInterval: 5000 });
  const report = useQuery({ queryKey: ['futures-report', id], queryFn: () => request<Report>(`${base}/${id}`), enabled: owner && !!id, refetchInterval: 3000 });
  const audit = useQuery({ queryKey: ['futures-audit', id], queryFn: () => request<Event[]>(`${base}/${id}/audit`), enabled: owner && !!id, refetchInterval: 3000 });
  const evidence = useQuery({ queryKey: ['futures-evidence', id], queryFn: () => request<unknown[]>(`${base}/${id}/evidence`), enabled: owner && !!id, refetchInterval: 5000 });
  const action = useMutation({ mutationFn: ({ path, body, json }: { path: string; body?: unknown; json?: string }) => request(`${base}/${id}/${path}`, 'POST', json === undefined ? body : JSON.parse(json) as unknown), onSuccess: () => { setDecision(null); void client.invalidateQueries({ queryKey: ['futures-report'] }); void client.invalidateQueries({ queryKey: ['futures-audit'] }); void client.invalidateQueries({ queryKey: ['futures-evidence'] }); } });
  const create = useMutation({ mutationFn: () => request<Report>(base, 'POST', JSON.parse(config) as unknown), onSuccess: r => { setParams({ mission: r.missionId }); void client.invalidateQueries({ queryKey: ['futures-list'] }); } });
  const r = report.data;
  const busy = action.isPending || create.isPending;
  return <><PageHeading eyebrow="PAPER / EVIDENCE" title="Futures simulation" description="Owner-approved configuration → backtest → approve evidence → simulate → reconcile. Paper only; target returns are aspirational." />
    {!owner ? <Panel title="Owner access required"><p>Trading records and decisions require an owner account in the configured workspace.</p></Panel> : <>
      <ErrorNotice error={list.error || report.error || audit.error || evidence.error || action.error || create.error} />
      <Panel title="Paper missions"><label>Choose a paper account<select value={id} onChange={e => { setParams(e.target.value ? { mission: e.target.value } : {}); setDecision(null); }}><option value="">Select account</option>{list.data?.map(m => <option key={m.missionId} value={m.missionId}>{m.missionId.slice(0, 8)} · {m.status}</option>)}</select></label><p>Ordinary agent missions are reports; they do not create a trading account.</p></Panel>
      <Panel title="Create a paper mission"><p>Supply verified contract specifications, margin, costs, deadline and risk limits. Limits are dollar amounts; a 10% drawdown limit on the initial $1,000 wallet is $100. The configuration is immutable after creation. Research selects among momentum lookbacks 2, 3 and 5.</p><details><summary>Advanced configuration JSON</summary><form onSubmit={e => { e.preventDefault(); create.mutate(); }}><label>MissionConfig JSON<textarea rows={12} required value={config} onChange={e => setConfig(e.target.value)} placeholder={'{"initialCapital":1000,"targetEquity":10000,"deadline":"ISO timestamp", "instruments":["verified contract specifications"], "maximumDrawdown":100, "...":"all required configuration fields"}'} /></label><button className="primary" disabled={busy}>Save configuration</button></form><p>All contract and risk fields are required. No exchange specifications or strategy results are assumed.</p></details></Panel>
      {r && <>
        <div className="mission-stage" role="status"><strong>{tradingOutcome(r.outcome)}</strong><p>Ledger snapshot: {date(r.reportedAt)} · Feed: {r.health} {r.stopReason && `· Stop reason: ${r.stopReason}`}</p>{r.liquidationPending && <p>Positions remain open. Reliable data and execution permission are required to finish closing them.</p>}</div>
        <div className="metrics-grid three"><div className="metric"><span>LEDGER EQUITY</span><strong>{money(r.equity)}</strong><small>Net P&amp;L {money(r.netPnl)}</small></div><div className="metric"><span>CURRENT DRAWDOWN</span><strong>{money(r.drawdown)} · {r.drawdownPercent.toFixed(2)}%</strong><small>Peak equity {money(r.peakEquity)} · maximum observed {money(r.maximumDrawdown)}</small></div><div className="metric"><span>BALANCE TARGET PROGRESS</span><strong>{r.targetProgressPercent.toFixed(2)}%</strong><small>Gain relative to initial capital and target; separate from deadline</small></div></div>
        <Panel title="Configuration and approvals"><Records title="Review exact configuration and limits" value={r.configuration} /><p>Configuration approval: {r.configurationApproved ? 'Approved' : 'Pending'}. Evaluation approval: {r.evaluationApproved ? 'Approved' : 'Pending'}.</p><div className="trading-actions">
          <button className="secondary" disabled={busy || r.configurationApproved || r.status !== 'CREATED'} onClick={() => setDecision('approve-configuration')}>Review research approval</button>
          <button className="secondary" disabled={busy || !r.evaluation?.passed || r.evaluationApproved || !['CREATED', 'PAUSED'].includes(r.status)} onClick={() => setDecision('approve-evaluation')}>Review trading approval</button>
          <button className="primary" disabled={busy || !r.evaluationApproved || !!r.stopReason || !['CREATED', 'PAUSED'].includes(r.status)} onClick={() => action.mutate({ path: 'start' })}>Start / resume simulation</button>
          <button className="secondary" disabled={busy || r.status !== 'RUNNING'} onClick={() => action.mutate({ path: 'pause' })}>Pause</button>
          <button className="secondary" disabled={busy || ['COMPLETED', 'STOPPING'].includes(r.status)} onClick={() => action.mutate({ path: 'stop' })}>Stop and close positions</button>
          <button className="secondary" disabled={busy || r.status === 'COMPLETED'} onClick={() => action.mutate({ path: 'tick' })}>Reconcile now</button>
        </div>{decision && <div className="mission-stage"><strong>{decision === 'approve-configuration' ? 'Approve this configuration for research only' : 'Approve this exact passing backtest for paper trading'}</strong><Records title="Evidence being approved" value={decision === 'approve-configuration' ? r.configuration : r.evaluation} /><p>No live orders or deposits are enabled. Limits cannot be raised on this account.</p><button className="primary" disabled={busy} onClick={() => action.mutate({ path: decision, body: { fingerprint: decision === 'approve-configuration' ? r.configurationFingerprint : r.evaluation?.fingerprint } })}>Confirm owner approval</button><button className="secondary" onClick={() => setDecision(null)}>Cancel</button></div>}</Panel>
        <Panel title="Backtest evidence"><p>Training selects a strategy; separate chronological validation tests it. Each evaluation resets trading approval.</p>{r.evaluation && <><strong>{r.evaluation.passed ? 'Passed validation' : 'Failed validation'} · {r.evaluation.strategyVersion}</strong><p>{r.evaluation.reason}</p><Records title="Backtest calculations" value={r.evaluation} /></>}<Records title="Stored datasets and evaluation history" value={evidence.data ?? []} /><form onSubmit={e => { e.preventDefault(); action.mutate({ path: 'evaluate', json: dataset }); }}><label>Training and validation JSON<textarea rows={5} value={dataset} onChange={e => setDataset(e.target.value)} placeholder='{"training":[...],"validation":[...]}' required /></label><button className="secondary" disabled={busy || !r.configurationApproved || !['CREATED', 'PAUSED'].includes(r.status)}>Run backtest</button></form></Panel>
        <Panel title="Wallet and trade records"><p>Fees: {money(r.fees)} · Embedded slippage: {money(r.slippage)} · Initial margin: {money(r.initialMarginUsed)} · Maintenance margin: {money(r.maintenanceMargin)} · Closed trades: {r.closedTrades}</p><Records title="Open positions" value={r.positions} /><Records title="Orders" value={r.orders} /><Records title="Fills and costs" value={r.fills} /><p>ACCOUNT_MARKED events below provide the timestamped equity history. Market gaps can exceed a stop threshold; limits trigger shutdown rather than guarantee a maximum loss.</p></Panel>
        <Panel title="Market data"><p>Scheduled worker: {r.workerEnabled ? 'enabled' : 'disabled · manual reconciliation only'}. Provider: {r.feedConfigured ? 'configured' : 'not configured · no automatic market data'}.</p><p>The operator-configured feed runs when the futures worker is enabled. An unavailable feed holds execution. To test manually, ingest trusted chronological bars matching the approved source.</p><form onSubmit={e => { e.preventDefault(); action.mutate({ path: 'bars', json: bars }); }}><label>OHLCV bar array<textarea rows={4} value={bars} onChange={e => setBars(e.target.value)} placeholder='[{"symbol":"...","startTime":"...","endTime":"...","source":"..."}]' required /></label><button className="secondary" disabled={busy || r.status === 'COMPLETED'}>Store bars</button></form></Panel>
        <section className="mission-console trading-console" aria-label="Trading event logs"><header className="mission-console-header"><button className="mission-console-toggle" aria-expanded={logsOpen} onClick={() => setLogsOpen(!logsOpen)}>Paper-engine logs · {audit.data?.length ?? 0} events · {logsOpen ? 'Collapse' : 'Expand'}</button></header>{logsOpen && <div className="mission-console-lines">{audit.data?.map(e => <div className="console-line" key={e.id}><time>{date(e.created_at)}</time><span>{e.event_type}</span><Records title="Recorded evidence" value={e.details} /></div>)}</div>}</section>
      </>}
    </>}
  </>;
}
