import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, NavLink, useParams } from 'react-router-dom';
import { Background, Controls, ReactFlow } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { Empty, ErrorNotice, Metric, PageHeading, Panel, Status, date, money } from '../../components/Shared';
import { ApiError } from '../../api/client';
import { operationsApi } from './api';

const tabs = ['overview', 'topology', 'agents', 'workflows', 'traces', 'incidents', 'costs', 'connectors', 'tenants'] as const;
function Pagination({ offset, count, onChange }: { offset: number; count: number; onChange: (offset: number) => void }) {
 return <div className="operations-pagination"><button disabled={!offset} onClick={() => onChange(Math.max(0, offset - 50))}>Previous</button><span>Page {offset / 50 + 1}</span><button disabled={count < 50} onClick={() => onChange(offset + 50)}>Next</button></div>;
}
export function OperationsPage({ elevated = false }: { elevated?: boolean }) {
 const { view: selectedView = 'overview', correlationId } = useParams();
 const view = correlationId ? 'traces' : selectedView;
 const [offset, setOffset] = useState(0);
 const client = useQueryClient();
 const acknowledge = useMutation({ mutationFn: operationsApi.acknowledge, onSuccess: () => { void client.invalidateQueries({ queryKey: ['operations'] }); } });
 const incidents = useQuery({ queryKey: ['operations', 'incidents', offset], queryFn: () => operationsApi.incidents(offset), enabled: view === 'incidents', refetchInterval: 5000 });
 const connectors = useQuery({ queryKey: ['operations', 'connectors', offset], queryFn: () => operationsApi.connectors(offset), enabled: view === 'connectors', refetchInterval: 10000 });
 const costs = useQuery({ queryKey: ['operations', 'costs', offset], queryFn: () => operationsApi.costs(offset), enabled: view === 'costs', refetchInterval: 10000 });
 const summary = useQuery({ queryKey: ['operations', 'summary'], queryFn: operationsApi.summary, refetchInterval: 5000 });
 const agents = useQuery({ queryKey: ['operations', 'agents', offset], queryFn: () => operationsApi.agents(offset), enabled: view === 'agents', refetchInterval: 5000 });
 const workflows = useQuery({ queryKey: ['operations', 'workflows', offset], queryFn: () => operationsApi.workflows(offset), enabled: view === 'workflows', refetchInterval: 5000 });
 const topology = useQuery({ queryKey: ['operations', 'topology'], queryFn: operationsApi.topology, enabled: view === 'topology', refetchInterval: 10000 });
 const traces = useQuery({ queryKey: ['operations', 'traces', offset], queryFn: () => operationsApi.traces(offset), enabled: view === 'traces' && !correlationId, refetchInterval: 5000, retry: (attempt, error) => !(error instanceof ApiError && error.status === 403) && attempt < 2 });
 const trace = useQuery({ queryKey: ['operations', 'trace', correlationId, offset], queryFn: () => operationsApi.trace(correlationId!, offset), enabled: !!correlationId, refetchInterval: 5000, retry: (attempt, error) => !(error instanceof ApiError && [403, 404].includes(error.status)) && attempt < 2 });
 const data = summary.data;
 const traceForbidden = traces.error instanceof ApiError && traces.error.status === 403;
 return <>
  <PageHeading eyebrow="LIVE OPERATIONS / AGENTOPS" title="Operations" description="Workspace execution, approvals and operational evidence." action={<button onClick={() => { void summary.refetch(); }}>Refresh</button>} />
  <nav className="operations-tabs" aria-label="Operations views">{tabs.map(tab => <NavLink key={tab} to={tab === 'overview' ? '/operations' : `/operations/${tab}`} end onClick={() => setOffset(0)}>{tab}</NavLink>)}</nav>
  <ErrorNotice error={summary.error} />
  {summary.isPending && <p role="status">Loading workspace operations…</p>}
  {summary.isError && <p>Operations data is unavailable. Last successful values may be stale.</p>}
  {data && <><p><Status value={data.health} /> <small>Updated {date(data.generatedAt)} · Refreshed every 5 seconds</small></p>
   <div className="operations-kpis"><Metric label="Active workflows" value={data.activeWorkflows} /><Metric label="Pending approvals" value={data.waitingApprovals} /><Metric label="Failed runs / hour" value={data.failedRunsLastHour} /><Metric label="Estimated spend today (UTC)" value={money(Number(data.estimatedSpendTodayUsd))} /></div></>}
  {data && data.incidentsOpen > 0 && <p role="status"><Link to="/operations/incidents">{data.incidentsOpen} open operational incidents →</Link></p>}
  {view === 'overview' && data && <Panel title="Workspace evidence"><p>Tenant: {data.scope.tenantId}<br />Workspace: {data.scope.workspaceId}</p><p>{data.telemetryEventsLastHour} operational events recorded in the last hour.</p><p>Telemetry collector: <Status value={data.observabilityHealth} /></p><p>Agent duration p95: {data.agentLatencyP95Ms === null ? 'No samples' : `${Math.round(data.agentLatencyP95Ms)} ms`}</p><Link to="/approvals">Review pending approvals →</Link></Panel>}
  {view === 'agents' && <Panel title="Registered agents"><ErrorNotice error={agents.error} />{agents.isPending ? <p>Loading agents…</p> : agents.data?.length ? <div className="operations-list">{agents.data.map(a => <Link key={a.id} to={`/agents/${encodeURIComponent(a.id)}`}><span>{a.label}</span><Status value={a.status} /></Link>)}</div> : !agents.error && <Empty title="No registered agents" />}<Pagination offset={offset} count={agents.data?.length ?? 0} onChange={setOffset} /></Panel>}
  {view === 'workflows' && <Panel title="Workflow fleet"><ErrorNotice error={workflows.error} />{workflows.isPending ? <p>Loading workflows…</p> : workflows.data?.length ? <div className="operations-list">{workflows.data.map(w => <div className="operations-workflow" key={w.id}><Link to={`/missions/${w.mission_id}`}><span>{w.id}<small>{date(w.created_at)} · {w.engine}</small></span></Link><Status value={w.status} />{w.correlation_id ? <Link to={`/operations/traces/${encodeURIComponent(w.correlation_id)}`} onClick={() => setOffset(0)}>View trace →</Link> : <small>Trace unavailable</small>}</div>)}</div> : !workflows.error && <Empty title="No workflows yet" />}<Pagination offset={offset} count={workflows.data?.length ?? 0} onChange={setOffset} /></Panel>}
  {view === 'topology' && <Panel title="Registered topology"><ErrorNotice error={topology.error} /><p>Nodes represent registered agents and model routes. Edges represent configured dependencies.</p>{topology.data && <div className="operations-graph"><ReactFlow nodes={topology.data.nodes.map((node, index) => ({ id: node.id, position: { x: (index % 4) * 240, y: Math.floor(index / 4) * 100 }, data: { label: `${node.label} · ${node.status}` } }))} edges={topology.data.edges.map((edge, index) => ({ id: String(index), source: edge.source, target: edge.target, label: edge.relation }))} fitView nodesDraggable={false}><Background /><Controls /></ReactFlow></div>}</Panel>}
  {view === 'traces' && !correlationId && <Panel title="Trace explorer">{traceForbidden ? <Empty title="Elevated role required" detail="Workspace trace inspection requires OWNER, ADMIN or OPERATOR access." /> : <><ErrorNotice error={traces.error} />{traces.isPending ? <p>Loading traces…</p> : traces.data?.length ? <div className="operations-list">{traces.data.map(t => <Link key={t.correlation_id} to={`/operations/traces/${encodeURIComponent(t.correlation_id)}`} onClick={() => setOffset(0)}><span>{t.correlation_id}<small>{date(t.last_seen)}</small></span><span>{t.event_count} events</span></Link>)}</div> : !traces.error && <Empty title="No traces recorded" detail="Run a workflow or issue a scoped API request to produce operational evidence." />}<Pagination offset={offset} count={traces.data?.length ?? 0} onChange={setOffset} /></>}</Panel>}
  {view === 'incidents' && <Panel title="Operational incidents"><ErrorNotice error={incidents.error || acknowledge.error} />{incidents.isPending ? <p>Loading incidents…</p> : incidents.data?.length ? incidents.data.map(i => <div className="operations-event" key={i.id}><strong>{i.title}</strong><Status value={i.status} /><small>{i.severity} · {date(i.detected_at)}</small>{i.status === 'OPEN' && elevated && <button disabled={acknowledge.isPending} onClick={() => acknowledge.mutate(i.id)}>Acknowledge incident</button>}</div>) : !incidents.error && <Empty title="No incidents recorded" />}<Pagination offset={offset} count={incidents.data?.length ?? 0} onChange={setOffset} /></Panel>}
  {view === 'connectors' && <Panel title="Connector health"><ErrorNotice error={connectors.error} />{connectors.isPending ? <p>Loading connectors…</p> : connectors.data?.length ? connectors.data.map(c => <div className="operations-event" key={c.id}><strong>{c.name} · {c.provider}</strong><Status value={c.status} /><span>{c.check_status ?? 'Health check unavailable'}</span><small>Last check: {date(c.last_health_check_at)}</small></div>) : !connectors.error && <Empty title="No connectors installed" />}<Pagination offset={offset} count={connectors.data?.length ?? 0} onChange={setOffset} /></Panel>}
  {view === 'costs' && <Panel title="Estimated agent/model costs today (UTC)"><ErrorNotice error={costs.error} />{costs.isPending ? <p>Loading costs…</p> : costs.data?.length ? costs.data.map((c, index) => <div className="operations-event" key={`${c.agent_id}-${c.model_name}-${index}`}><strong>{c.agent_id} · {c.model_name ?? 'Model unavailable'}</strong><span>{money(Number(c.estimated_cost_usd))} · {c.runs} runs</span></div>) : !costs.error && <Empty title="No agent costs recorded today" />}<Pagination offset={offset} count={costs.data?.length ?? 0} onChange={setOffset} /></Panel>}
  {view === 'tenants' && data && <Panel title="Authorized tenant scope"><p>Tenant: {data.scope.tenantId}</p><p>Workspace: {data.scope.workspaceId}</p><Status value={data.health} /><p>{data.activeWorkflows} active workflows · {data.waitingApprovals} waiting approvals</p></Panel>}
  {correlationId && <Panel title={`Trace ${correlationId}`} action={<Link to="/operations/traces" onClick={() => setOffset(0)}>All traces</Link>}><ErrorNotice error={trace.error} />{trace.isPending ? <p>Loading trace…</p> : trace.data?.map(event => <div className="operations-event" key={event.event_id}><Status value={event.status} /><strong>{event.event_type}</strong><small>{date(event.occurred_at)} · {event.actor_id}</small><code>{event.trace_id ?? 'Distributed trace unavailable'}</code></div>)}<Pagination offset={offset} count={trace.data?.length ?? 0} onChange={setOffset} /></Panel>}
 </>;
}
